const reduced = matchMedia('(prefers-reduced-motion: reduce)');
const mobile = matchMedia('(max-width: 640px)');
const menu = document.querySelector('.menu'), nav = document.querySelector('nav');
menu.addEventListener('click', () => {const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);menu.textContent=open?'Kapat ×':'Menü +'});
nav.querySelectorAll('a').forEach(a=>{if(new URL(a.href).pathname===location.pathname)a.setAttribute('aria-current','page')});
addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menü +'}});
if(!reduced.matches){document.body.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${el.classList.contains('brand-card')?(i%4)*70:0}ms`;observer.observe(el)})}
let navigating=false;
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||a.target||a.hasAttribute('download')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;const url=new URL(a.href);if(url.origin!==location.origin||url.pathname===location.pathname||reduced.matches)return;e.preventDefault();if(navigating)return;navigating=true;const curtainWords=['FEVZİPAŞA.','KEŞFET.','TANIŞ.','DESTEKLE.'];let lastWord='';try{lastWord=sessionStorage.getItem('curtainWord')||''}catch{}const options=curtainWords.filter(w=>w!==lastWord);const word=options[Math.floor(Math.random()*options.length)];try{sessionStorage.setItem('curtainWord',word)}catch{}const curtainText=document.querySelector('.route-curtain span');if(curtainText)curtainText.textContent=word;const curtainThemes={'FEVZİPAŞA.':['var(--orange)','var(--yellow)'],'KEŞFET.':['var(--pink)','var(--ink)'],'TANIŞ.':['var(--blue)','var(--yellow)'],'DESTEKLE.':['var(--yellow)','var(--orange)']};const curtain=document.querySelector('.route-curtain');curtain.style.background=curtainThemes[word][0];curtain.style.color=curtainThemes[word][1];curtain.classList.add('active');setTimeout(()=>location.assign(a.href),320)});
addEventListener('pageshow',()=>{navigating=false;document.querySelector('.route-curtain').classList.remove('active')});
let ticking=false;
const stacks=[...document.querySelectorAll('[data-stack]')], rails=[...document.querySelectorAll('[data-horizontal]')], editorial=[...document.querySelectorAll('.editorial-image')];
function clamp(n,min=0,max=1){return Math.max(min,Math.min(max,n))}
function updateScroll(){ticking=false;const vh=innerHeight;const progress=scrollY/Math.max(1,document.documentElement.scrollHeight-vh);document.querySelector('.progress').style.transform=`scaleX(${progress})`;if(reduced.matches)return;
 for(const el of stacks){const rect=el.getBoundingClientRect();if(rect.bottom<0||rect.top>vh)continue;const top=mobile.matches?72:90,p=clamp((top-rect.top)/(el.offsetHeight-vh+top));const a=el.querySelector('.stack-one'),b=el.querySelector('.stack-two'),c=el.querySelector('.stack-three');a.style.transform=`translateY(${-p*35}px) rotate(${-7+p*10}deg) scale(${1-p*.08})`;b.style.transform=`translateY(${(1-clamp(p*2.5))*130}%) rotate(${7-p*9}deg)`;c.style.transform=`translateY(${(1-clamp((p-.5)*2))*150}%) rotate(${-3+p*5}deg)`;const i=p<.33?0:p<.7?1:2;el.querySelector('.step-number').textContent=`0${i+1}`;el.querySelector('.step-label').textContent=['BİÇİM & DOKU','RENK & DESEN','IŞIK & YAŞAM'][i];el.querySelector('.step-line i').style.transform=`scaleX(${p})`}
 for(const el of rails){const track=el.querySelector('.gallery-track');if(mobile.matches){track.style.transform='';continue}const rect=el.getBoundingClientRect();const p=clamp((90-rect.top)/(el.offsetHeight-vh+90));const overflow=Math.max(0,track.scrollWidth-innerWidth);track.style.transform=`translateX(${-p*overflow}px)`}
 for(const el of editorial){const rect=el.getBoundingClientRect();if(rect.bottom<0||rect.top>vh)continue;const p=clamp((vh-rect.top)/(vh+rect.height));el.querySelector('img').style.transform=`translateY(${(p-.5)*35}px) scale(1.1)`}
}
addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(updateScroll)}},{passive:true});addEventListener('resize',updateScroll);reduced.addEventListener('change',()=>location.reload());updateScroll();
const viewer=document.getElementById('viewer'),content=viewer.querySelector('.dialog-content');
function show(contentNodes){content.replaceChildren(...contentNodes);viewer.showModal()}
function paragraph(text,className){const p=document.createElement('p');p.textContent=text;if(className)p.className=className;return p}
function photo(src,alt){const img=document.createElement('img');img.src=src;img.alt=alt;return img}
let brandsPromise;
async function getBrands(){brandsPromise??=fetch('/brands.json').then(r=>{if(!r.ok)throw new Error('Katılımcılar yüklenemedi');return r.json()});return brandsPromise}
document.querySelectorAll('[data-photo]').forEach(button=>button.addEventListener('click',()=>show([photo(button.dataset.photo,button.dataset.caption),paragraph(button.dataset.caption,'dialog-caption')])));
document.querySelectorAll('[data-brand]').forEach(button=>button.addEventListener('click',async()=>{try{const brands=await getBrands(),b=brands[Number(button.dataset.brand)];const wrap=document.createElement('div');wrap.className='brand-detail';const info=document.createElement('div'),h=document.createElement('h2');h.textContent=b.name;info.append(paragraph(b.category,'eyebrow'),h,paragraph(b.description));if(b.url){const link=document.createElement('a');link.href=b.url;link.textContent='Web sitesine git ↗';link.className='text-link';link.target='_blank';link.rel='noopener noreferrer';info.append(link)}info.append(paragraph('Ürün fotoğrafı temsilidir. Gerçek marka görselleri eklenecektir.','asset-note'));wrap.append(photo(b.image,b.category+' temsili görsel'),info);show([wrap])}catch{show([paragraph('Katılımcı bilgisi yüklenemedi. Lütfen tekrar dene.','dialog-caption')])}}));
viewer.querySelector('.dialog-close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer){const rect=viewer.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)viewer.close()}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.participant-list .brand-card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter;card.classList.add('visible');if(!card.hidden&&!reduced.matches)card.animate([{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'ease-out'})})}));
const calendar=document.getElementById('calendar');calendar?.addEventListener('click',()=>{const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Fevzipasa//Tasarim Pazari//TR','CALSCALE:GREGORIAN'];for(let day=9;day<=11;day++){const date='202610'+String(day).padStart(2,'0');lines.push('BEGIN:VEVENT',`UID:fevzipasa-2026-${day}@fevzipasa.local`,'DTSTAMP:20261006T200000Z','DTSTART:'+date+'T080000Z','DTEND:'+date+'T180000Z','SUMMARY:Fevzipaşa Tasarım Pazarı','LOCATION:Fevzipaşa Mahallesi\\, Çanakkale','END:VEVENT')}lines.push('END:VCALENDAR');const url=URL.createObjectURL(new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='fevzipasa-tasarim-pazari.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('status').textContent='Takvim dosyası indirildi. Takvim uygulamanda açabilirsin.'});
// Yerel geliştirmede dosyalar değişince sayfayı yenile.
if(['127.0.0.1','localhost'].includes(location.hostname)){let previous;let checking=false;setInterval(async()=>{if(checking||document.hidden||viewer.open)return;checking=true;try{const response=await fetch('/__version',{cache:'no-store'});const current=(await response.json()).version;if(previous&&current!==previous){const key='fevzipasa-scroll:'+location.pathname;sessionStorage.setItem(key,String(scrollY));location.reload()}previous=current}catch{}finally{checking=false}},1500);const key='fevzipasa-scroll:'+location.pathname,saved=sessionStorage.getItem(key);if(saved!==null){sessionStorage.removeItem(key);requestAnimationFrame(()=>scrollTo(0,Number(saved)))}}
if(location.pathname==='/hikaye'){(async()=>{const heroTitle=document.querySelector('.hero-title');if(!heroTitle)return;const phrases=[['TASARIM','SOKAĞA ÇIKIYOR.'],['ŞEHİR','TASARIMCILARIYLA','BULUŞUYOR.']];const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const ease='cubic-bezier(.65,0,.35,1)';const move=(from,to,duration)=>Promise.all([...heroTitle.querySelectorAll('i')].map(el=>el.animate([{transform:`translateY(${from})`},{transform:`translateY(${to})`}],{duration,easing:ease,fill:'forwards'}).finished));const render=(lines,y)=>{heroTitle.innerHTML=lines.map(line=>`<span><i style="animation:none;transform:translateY(${y})">${line}</i></span>`).join('')};let index=0;while(heroTitle.isConnected){await wait(2200);index=(index+1)%phrases.length;if(reduced.matches){render(phrases[index],'0');continue}await move('0','-3.2em',750);render(phrases[index],'3.2em');await move('3.2em','0',900)}})()}
if(document.body.classList.contains('home')){(async()=>{const lines=[...document.querySelectorAll('.hero .hero-title i')];if(lines.length!==3)return;const sets=[['FEVZİPAŞA','TASARIM','PAZARI'],['KEŞFET','TANIŞ','DESTEKLE']];const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const exitAll=(duration,stagger=0)=>Promise.all(lines.map((el,i)=>el.animate([{transform:'translateY(0)'},{transform:'translateY(-115%)'}],{duration:stagger?duration+i*150:duration,delay:i*stagger,easing:'cubic-bezier(.55,0,1,.45)',fill:'forwards'}).finished));const enter=stagger=>Promise.all(lines.map((el,i)=>el.animate(stagger?[{transform:'translateY(115%)',easing:'cubic-bezier(.2,.7,.4,1)'},{transform:'translateY(10%)',offset:.3,easing:'cubic-bezier(.1,.6,.2,1)'},{transform:'translateY(0)'}]:[{transform:'translateY(115%)'},{transform:'translateY(0)'}],{duration:stagger?520+i*200:1100,delay:i*stagger,easing:stagger?'linear':'cubic-bezier(.16,1,.3,1)',fill:'both'}).finished));let index=0;await wait(1000);while(document.body.contains(lines[0])){await wait(index===0?1100:2600);if(reduced.matches)continue;await exitAll(index===0?320:700,index===0?0:150);index=(index+1)%sets.length;lines.forEach((el,i)=>{el.style.animation='none';el.textContent=sets[index][i]});await enter(index===1?290:0)}})()}